import os
from pathlib import Path
import glob
from datetime import datetime

# animals_dir = str(Path(os.getcwd()).parent) + '\\Classes\\Animals\\pngs\\';

# animals = []
# for file in glob.iglob(animals_dir + '**.png'):
# 	animal = file[len(animals_dir):-4];
# 	animals.append(animal)

# print('found ' + str(len(animals)) + ' pictures of animals. Generating file...') 	
	
# file = open(os.getcwd() + '//pictures_animals.js','w')

# file.write('// This file is autogenerated from the images located at ' + animals_dir + ' by running the file generate_picture_arrays.py\n')
# file.write('// Please don\'t edit this file directly to avoid errors.\n')
# file.write('// Last creation date: ' + str(datetime.today().strftime('%Y-%m-%d-%H:%M:%S\n')))
# file.write('let ANIMAL_NAMES = [' +  ' '.join(map(lambda x: '\'' + x + '\',',animals)) + '];')

# file.close()

main_dir = str(Path(os.getcwd())) + '\\images'
dirs = {
"buildings": '/skyscrapers/',
"ghosts": '/ghosts/',
"invaders": '/invaders/',
"projectiles": '/projectiles/',
"space_bgs": '/space_bg/',
"backgrounds": '/',
"old_space_bg": '/',
"monsters": '/',
"old_ghosts": '/'
}
syntax = {
"buildings": 'skyscraper{num}.png',
"ghosts": '{valid_name}{num}.png',
"invaders": 'invader{valid_name}.png',
"projectiles": '{valid_name}_projectile',
"space_bgs": 'space{num}.jpg',
"backgrounds": 'background{num}.png',
"old_space_bg": 'bg{num}.png',
"monsters": 'monster{num}.png',
"old_ghosts": 'ghost{num}.png'
}

lines = []

lines.append('let PICTURE_CONFIG = {')

for key in dirs.keys():
	lines.append('\t'+ key + ': {')
	lines.append('\t\tpath: "' + dirs[key] + '",')
	# count how many images in the directory

	print(Path(os.getcwd() + main_dir + dirs[key]))
	print(syntax[key].replace('{num}', '*').replace('{valid_name}','*'))


	lines.append(f'\t\tnum: {0},')
	lines.append(f'\t\tsyntax: "{syntax[key]}",')
	lines.append('\t},')

lines.append('}')
print(lines)

file = open(os.getcwd() + '//image_config.js','w')
file.write('// This file is autogenerated from the images located at ' + main_dir + ' by running the file generate_picture_arrays.py\n')
file.write('// Please don\'t edit this file directly to avoid errors.\n')
file.write('// Last creation date: ' + str(datetime.today().strftime('%Y-%m-%d-%H:%M:%S\n')))
for line in lines:
	file.write(line + '\n')
file.close()

print('Done.')