import os
from pathlib import Path
import glob
from datetime import datetime
import re

old_file = open(os.getcwd() + '//image_config.js','r')
old_lines = old_file.read().split('\n')
external_lines = []

external_part = False
for line in old_lines:
	if external_part:
		external_lines.append(line)
		if 'END EXTERNAL PICTURES' in line:
			break
	else:
		if 'BEGIN EXTERNAL PICTURES' in line:
			external_part = True
			external_lines.append(line)

main_dir = str(Path(os.getcwd())) + '\\images'
dirs = {
"buildings": '/buildings/',
"ghosts": '/ghosts/',
"invaders": '/invaders/',
"projectiles": '/projectiles/',
"space_bgs": '/space_bgs/',
"backgrounds": '/',
"old_space_bg": '/',
"monsters": '/',
"old_ghosts": '/'
}
syntax = {
"buildings": 'skyscraper{num}.png',
"ghosts": '{valid_name}{num}.png',
"invaders": 'invader{valid_name}.png',
"projectiles": '{valid_name}_projectile.png',
"space_bgs": 'space{num}.jpg',
"backgrounds": 'background{num}.jpg',
"old_space_bg": 'bg{num}.jpg',
"monsters": 'monster{num}.png',
"old_ghosts": 'ghost{num}.png'
}

lines = []

lines.append('let PICTURE_CONFIG = {')

for key in dirs.keys():
	lines.append('\t'+ key + ': {')
	lines.append('\t\tpath: "' + dirs[key] + '",')
	# count how many images in the directory
	img_path = str(Path(main_dir + dirs[key]))+ '\\*'
	num_of_images = 0
	list_of_names = []
	print(img_path)
	for image in glob.iglob(img_path):
		img_name = image.split('\\')[-1]
		regex = syntax[key].replace('{num}', '\d+').replace('{valid_name}','\w+').replace('.','\.')
		search = re.match(rf"{regex}",img_name)
		if search:
			num_of_images += 1
			word = search.group()
			if 'valid_name' in syntax[key]:
				to_remove = syntax[key].replace('{valid_name}','').split('.')
				list_of_names.append(word.replace(to_remove[0],'').replace('.' + to_remove[1],''))
	if 'valid_name' in syntax[key]:
		lines.append(f'\t\tvalid_names: {list_of_names},')
				

	lines.append(f'\t\tnum: {num_of_images},')
	lines.append(f'\t\tsyntax: "{syntax[key]}",')
	lines.append('\t},')

lines.append('}')
# print(lines)

file = open(os.getcwd() + '//image_config.js','w')
file.write('//=== BEGIN INTERNAL PICTURES ===\n\n')
file.write('// This file is autogenerated from the images located at ' + main_dir + ' by running the file generate_picture_arrays.py\n')
file.write('// Please don\'t edit this file directly to avoid errors.\n')
file.write('// Last creation date: ' + str(datetime.today().strftime('%Y-%m-%d-%H:%M:%S\n')) + '\n')
for line in lines:
	file.write(line + '\n')

file.write('//=== END INTERNAL PICTURES ===\n\n')

for line in external_lines:
	file.write(line + '\n')
file.close()

print('Done.')