import os
from pathlib import Path
import glob
from datetime import datetime

# animals_dir = str(Path(os.getcwd()).parent) + '\\Classes\\Animals\\pngs\\';

# animals = []
# for file in glob.iglob(animals_dir + '**.png'):
# 	animal = file[len(animals_dir):-4];
# 	animals.append(animal)

# print('found ' + str(len(animals)) + ' pictures of animals. Generating file...') 	
	
# file = open(os.getcwd() + '//pictures_animals.js','w')

# file.write('// This file is autogenerated from the images located at ' + animals_dir + ' by running the file generate_picture_arrays.py\n')
# file.write('// Please don\'t edit this file directly to avoid errors.\n')
# file.write('// Last creation date: ' + str(datetime.today().strftime('%Y-%m-%d-%H:%M:%S\n')))
# file.write('let ANIMAL_NAMES = [' +  ' '.join(map(lambda x: '\'' + x + '\',',animals)) + '];')

# file.close()

main_dir = str(Path(os.getcwd())) + '\\images'
dirs = {
"buildings": '\\buidlings\\',
"ghosts": '\\ghosts\\',
"invaders": '\\invaders\\',
"projectiles": '\\projectiles\\',
"space_bgs": '\\space_bg\\',
"backgrounds": '\\',
"old_space_bg": '\\'
}


print(dirs['buildings'])




print('Done.')