//=== BEGIN INTERNAL PICTURES ===

// This file is autogenerated from the images located at C:\Users\1337\Documents\Programming\JavaScript\testgames\images by running the file generate_picture_arrays.py
// Please don't edit this file directly to avoid errors.
// Last creation date: 2021-01-06-21:00:39

let IMAGE_CONFIG = {
	buildings: {
		path: "/buildings/",
		num: 14,
		syntax: "skyscraper{num}.png",
	},
	ghosts: {
		path: "/ghosts/",
		num: 30,
		syntax: "{valid_name}{num}.png",
		valid_names: ['yellow', 'rainbow', 'blue', 'evil', 'purple', 'green', 'orange', 'space', 'pink', 'red'],
	},
	invaders: {
		path: "/invaders/",
		num: 9,
		syntax: "invader{valid_name}.png",
		valid_names: ['yellow', 'blue', 'purple', 'white', 'green', 'black', 'orange', 'pink', 'red'],
	},
	projectiles: {
		path: "/projectiles/",
		num: 52,
		syntax: "{valid_name}_projectile.png",
		valid_names: ['krabbypatty', 'water', 'smellysocks', 'greenenergy', 'yarn', 'blueenergy', 'fairy3', 'fire', 'electric', 'fish', 'fairy2', 'ice', 'bullet', 'legored', 'dynamite', 'pear', 'ki', 'rock', 'torch', 'whitemagic', 'tornado', 'zeldabomb', 'arrow', 'onion', 'hairbrush', 'nuke', 'blackenergy', 'spaghetti', 'bluebird', 'fairy1', 'bluebeam', 'grenade', 'mamahaha', 'robin', 'baby_bottle', 'web', 'rainbow', 'pinkenergy', 'batarang', 'blacklego', 'poke', 'magic', 'spongebobdollar', 'stars', 'cashield', 'pixelshot', 'shuriken', 'knife', 'banana', 'apple', 'covid', 'yellowmagic'],
	},
	space_bgs: {
		path: "/space_bgs/",
		num: 14,
		syntax: "space{num}.jpg",
	},
	backgrounds: {
		path: "/",
		num: 30,
		syntax: "background{num}.jpg",
	},
	old_space_bg: {
		path: "/",
		num: 8,
		syntax: "bg{num}.jpg",
	},
	monsters: {
		path: "/",
		num: 54,
		syntax: "monster{num}.png",
	},
	old_ghosts: {
		path: "/",
		num: 11,
		syntax: "ghost{num}.png",
	},
	weapons: {
		path: "/weapons/",
		num: 16,
		syntax: "{valid_name}.png",
		valid_names: ['uzi', 'alienblaster', 'rpg', 'm16', 'deagle', 'awm', 'gun', 'revolver', 'glock', 'ak47', 'rpd', 'infinitygauntlet', 'mp5', 'remington', 'p90', 'minigun'],
	},
	cityscapes: {
		path: "/cityscapes/",
		num: 5,
		syntax: "city{num}.jpg",
	},
}
//=== END INTERNAL PICTURES ===

//=== BEGIN EXTERNAL PICTURES ===


// This section is autogenerated from the images located at D:\\Classes\Animals\pngs\ by running the file generate_external_picture_arrays.py
// Please don't edit this file directly to avoid errors.
// Last creation date: 2021-01-10-12:40:49

IMAGE_CONFIG.animals = {
	path: '../Classes/Animals/pngs/',
	num: 100,
	syntax: '{valid_name}.png',
	valid_names: ['ant', 'bear', 'bee', 'beetle', 'beluga', 'bull', 'butterfly', 'cat', 'caterpillar', 'chameleon', 'cheetah', 'chimpanzee', 'clown_fish', 'cobra', 'cockroach', 'cow', 'crab', 'crocodile', 'deer', 'dog', 'dolphin', 'dragonfly', 'duck', 'eagle', 'elephant', 'fish', 'fly', 'frog', 'galapagos_tortoise', 'giraffe', 'goat', 'goose', 'gorilla', 'grasshopper', 'hamster', 'hercules_beetle', 'hippo', 'horse', 'kangaroo', 'kitten', 'koala', 'komodo', 'leopard', 'lion', 'lionfish', 'lizard', 'lobster', 'monkey', 'moose', 'mosquito', 'mouse', 'octopus', 'orangutan', 'orca', 'otter', 'owl', 'ox', 'panda', 'parrot', 'penguin', 'pig', 'piranha', 'plankton', 'platypus', 'polar_bear', 'quail', 'rabbit', 'raccoon', 'red_panda', 'reindeer', 'rhino', 'salamander', 'scorpion', 'seahorse', 'seal', 'sea_turtle', 'shark', 'sheep', 'sloth', 'snail', 'snake', 'snow_leopard', 'spider', 'squid', 'squirrel', 'starfish', 'tadpole', 'tiger', 'tortoise', 'toucan', 'turtle', 'vulture', 'walrus', 'wasp', 'whale', 'white_tiger', 'wolf', 'worm', 'yak', 'zebra',]
};

//=== END EXTERNAL PICTURES ===


