//=== BEGIN INTERNAL PICTURES ===

// This file is autogenerated from the images located at D:\testgames\images by running the file generate_picture_arrays.py
// Please don't edit this file directly to avoid errors.
// Last creation date: 2020-11-28-13:00:27

let PICTURE_CONFIG = {
	buildings: {
		path: "/buildings/",
		num: 6,
		syntax: "skyscraper{num}.png",
	},
	ghosts: {
		path: "/ghosts/",
		valid_names: ['blue0', 'blue1', 'blue2', 'evil0', 'evil1', 'evil2', 'green0', 'green1', 'green2', 'orange0', 'orange1', 'orange2', 'pink0', 'pink1', 'pink2', 'purple0', 'purple1', 'purple2', 'rainbow0', 'rainbow1', 'rainbow2', 'red0', 'red1', 'red2', 'space0', 'space1', 'space2', 'yellow0', 'yellow1', 'yellow2'],
		num: 30,
		syntax: "{valid_name}{num}.png",
	},
	invaders: {
		path: "/invaders/",
		valid_names: ['black', 'blue', 'green', 'orange', 'pink', 'purple', 'red', 'white', 'yellow'],
		num: 9,
		syntax: "invader{valid_name}.png",
	},
	projectiles: {
		path: "/projectiles/",
		valid_names: ['apple', 'arrow', 'baby_bottle', 'banana', 'batarang', 'blackenergy', 'blacklego', 'bluebeam', 'bluebird', 'blueenergy', 'bullet', 'cashield', 'covid', 'dynamite', 'electric', 'fairy1', 'fairy2', 'fairy3', 'fire', 'fish', 'greenenergy', 'grenade', 'hairbrush', 'ice', 'knife', 'krabbypatty', 'legored', 'magic', 'mamahaha', 'nuke', 'onion', 'pear', 'pinkenergy', 'poke', 'rainbow', 'robin', 'rock', 'shuriken', 'spaghetti', 'stars', 'tornado', 'water', 'web', 'whitemagic', 'yarn', 'yellowmagic', 'zeldabomb'],
		num: 47,
		syntax: "{valid_name}_projectile.png",
	},
	space_bgs: {
		path: "/space_bgs/",
		num: 14,
		syntax: "space{num}.jpg",
	},
	backgrounds: {
		path: "/",
		num: 30,
		syntax: "background{num}.jpg",
	},
	old_space_bg: {
		path: "/",
		num: 8,
		syntax: "bg{num}.jpg",
	},
	monsters: {
		path: "/",
		num: 47,
		syntax: "monster{num}.png",
	},
	old_ghosts: {
		path: "/",
		num: 11,
		syntax: "ghost{num}.png",
	},
}
//=== END INTERNAL PICTURES ===

//=== BEGIN EXTERNAL PICTURES ===


// This section is autogenerated from the images located at D:\\Classes\Animals\pngs\ by running the file generate_external_picture_arrays.py
// Please don't edit this file directly to avoid errors.
// Last creation date: 2020-11-28-13:08:38

PICTURE_CONFIG.animals = {
	path: 'D://Classes/Animals/pngs/',
	num: 67,
	syntax: '{valid_name}.png',
	valid_names: ['ant', 'beluga', 'butterfly', 'cat', 'caterpillar', 'chameleon', 'cheetah', 'clownfish', 'cobra', 'cockroach', 'crab', 'crocodile', 'dog', 'dolphin', 'dragonfly', 'duck', 'eagle', 'elephant', 'fly', 'frog', 'galapagostortoise', 'giraffe', 'grasshopper', 'hercules_beetle', 'hippo', 'horse', 'kangaroo', 'koala', 'komodo', 'lion', 'lionfish', 'lizard', 'lobster', 'monkey', 'mosquito', 'octopus', 'orca', 'owl', 'panda', 'parrot', 'penguin', 'piranha', 'planktonreal', 'platypus', 'rabbit', 'rhino', 'salamander', 'scorpion', 'seahorse', 'seal', 'seaturtle', 'shark', 'sheep', 'sloth', 'snail', 'snake', 'spider', 'squid', 'starfish', 'tadpole', 'tiger', 'vulture', 'walrus', 'whale', 'whitetiger', 'worm', 'zebra',]
};

//=== END EXTERNAL PICTURES ===


