//=== BEGIN INTERNAL PICTURES ===

// This file is autogenerated from the images located at C:\Users\1337\Documents\Programming\JavaScript\testgames\images by running the file generate_picture_arrays.py
// Please don't edit this file directly to avoid errors.
// Last creation date: 2021-05-23-13:11:47

let IMAGE_CONFIG = {
	buildings: {
		path: "/buildings/",
		num: 14,
		syntax: "skyscraper{num}.png",
	},
	ghosts: {
		path: "/ghosts/",
		num: 30,
		syntax: "{valid_name}{num}.png",
		valid_names: ['purple', 'orange', 'red', 'rainbow', 'space', 'pink', 'evil', 'green', 'blue', 'yellow'],
	},
	invaders: {
		path: "/invaders/",
		num: 9,
		syntax: "invader{valid_name}.png",
		valid_names: ['black', 'white', 'purple', 'orange', 'red', 'pink', 'green', 'blue', 'yellow'],
	},
	projectiles: {
		path: "/projectiles/",
		num: 61,
		syntax: "{valid_name}_projectile.png",
		valid_names: ['poke', 'cashield', 'smellysocks', 'arrow', 'fairy3', 'krabbypatty', 'robin', 'whitemagic', 'diamondblock', 'tornado', 'torch', 'yarn', 'legored', 'batarang', 'cobblestoneblock', 'greenenergy', 'fish', 'katana', 'ice', 'bone', 'pinkenergy', 'pixelshot', 'leaf', 'spaghetti', 'dynamite', 'fairy1', 'fairy2', 'onion', 'magic', 'shuriken', 'web', 'grenade', 'bluebeam', 'spongebobdollar', 'blacklego', 'water', 'blackenergy', 'electric', 'baby_bottle', 'covid', 'hairbrush', 'yellowelectric', 'apple', 'pear', 'mamahaha', 'rainbow', 'zeldabomb', 'banana', 'blueenergy', 'fire', 'woodblock', 'bluebird', 'nuke', 'fist', 'rock', 'ki', 'stars', 'yellowmagic', 'grassblock', 'knife', 'bullet'],
	},
	space_bgs: {
		path: "/space_bgs/",
		num: 14,
		syntax: "space{num}.jpg",
	},
	backgrounds: {
		path: "/",
		num: 30,
		syntax: "background{num}.jpg",
	},
	old_space_bg: {
		path: "/",
		num: 8,
		syntax: "bg{num}.jpg",
	},
	monsters: {
		path: "/",
		num: 59,
		syntax: "monster{num}.png",
	},
	old_ghosts: {
		path: "/",
		num: 11,
		syntax: "ghost{num}.png",
	},
	weapons: {
		path: "/weapons/",
		num: 16,
		syntax: "{valid_name}.png",
		valid_names: ['awm', 'alienblaster', 'infinitygauntlet', 'mp5', 'revolver', 'remington', 'uzi', 'rpg', 'p90', 'gun', 'minigun', 'rpd', 'ak47', 'm16', 'glock', 'deagle'],
	},
	cityscapes: {
		path: "/cityscapes/",
		num: 5,
		syntax: "city{num}.jpg",
	},
	cardbacks: {
		path: "/cardbacks/",
		num: 20,
		syntax: "back{num}.jpg",
	},
	characters: {
		path: "/chars/",
		num: 75,
		syntax: "{valid_name}.png",
		valid_names: ['superman', 'shark', 'sofia', 'spongebob', 'squirtle', 'anna', 'dog', 'simba', 'venom', 'arceus', 'black_widow', 'pikachu', 'rapunzel', 'nakoruru', 'goku', 'sailor_moon', 'thanos', 'monkey_king', 'thor', 'tiger', 'tree', 'gundam', 'arlo', 'shoe', 'shrek', 'mr_krabs', 'hello_kitty', 'luffy', 'link', 'doraemon', 'olaf', 'zoro', 'genie', 'ultraman', 'hawkeye', 'hermione', 'snow_white', 'starfish', 'ant', 'elsa', 'emmet', 'spiderman', 'ultraman3', 'vision', 'wyldstyle', 'dolphin', 'sleeping_beauty', 'bananaman', 'ariel', 'hulk', 'ironman', 'mario', 'charizard', 'rainbow', 'baby', 'isabelle', 'optimus', 'dr_strange', 'zebra', 'ash', 'captain_marvel', 'harry_potter', 'captain_america', 'mewtwo', 'peppa_pig', 'monkey', 'cat', 'penguin', 'steve', 'ultraman2', 'batman', 'dead_fish', 'cinderella', 'rabbit', 'deadpool'],
	},
}
//=== END INTERNAL PICTURES ===

//=== BEGIN EXTERNAL PICTURES ===


// This section is autogenerated from the images located at C:\Users\1337\Documents\Programming\JavaScriptClasses\Animals\pngs\ by running the file generate_external_picture_arrays.py
// Please don't edit this file directly to avoid errors.
// Last creation date: 2021-05-23-13:36:45

IMAGE_CONFIG.animals = {
	path: '..Classes/Animals/pngs/',
	num: 0,
	syntax: '{valid_name}.png',
	valid_names: []
};

//=== END EXTERNAL PICTURES ===


