//TODO make this autogenerated


let PICTURE_CONFIG = {
    monsters: {
        path: '/',
        num: 47,
        syntax: 'monster{num}.png'
    },
    battle_backgrounds:{
        path: '/',
        num: 30,
        syntax: 'background{num}.png'
    },
    old_space_bg:{
        path: '/',
        num: 8,
        syntax: 'bg{num}.png'
    },
    old_ghosts:{
        path: '/',
        num: 11,
        syntax: 'ghost{num}.png'
    },
    ghosts:{
        path:'/ghosts/',
        num: 3,
        valid_names: ['blue','green','orange','pink','purple','red','yellow','rainbow','space','evil'],
        syntax: '{valid_name}{num}.png'
    },
    invaders:{
        path:'/invaders/',
        num: 0,
        valid_names: ['black','blue','green','orange','pink','purple','red','white','yellow'],
        syntax: 'invader{valid_name}.png',
    },
    space_backgrounds:{
        path: '/space_bgs/',
        num: 14,
        syntax: 'space{num}.jpg'
    },
    buildings:{
        path: '/buildings/',
        num: 6,
        syntax: 'skyscraper{num}.png'
    }

}