let override = [
//===============PHONICS===============

//['paul','cook','food','spoon','hook','boots','foot','august','autumn','paw','jaw','saw'],
//['park','horse','fork','nurse','skirt','singer','farmer','bird','arm','car','turtle'],
//['goat','coat','boat','cloak','clock','wall','green','grass','ball'],
//['flute','luke','prune','sue','blue','glue','fruit','suit','juice','cute','mule','cube'],
//['trousers','truck','train','strawberry','trash','tree','draw','drink','dragon','driver','drum','drawer'],
//['meat','sea','jeep','seat','green','feet','me','he','we','candy','happy','puppy'],
//['pie','tie','necktie','bite','nine','kite','hi','climb','blind','fly','cry','sky'],
//['sword','storm','morning','corn','hard','jar','star','card','her','spider','runner','dancer','purse','purple','turn','fur'],
//['tape','cake','lake','tail','mail','nail','day','hay','pay'],
['bone','rope','robe','soap','boat','coat','bowl','snow','row'],
//['food','spoon','boots','cook','hook','foot','august','autumn','paul','paw','jaw','saw'],
//['cloud','house','mouse','clown','cow','owl','oil','coin','soil','joy','boy','toys'],

//================ESLS=================

//['projector','whiteboard','marker pen','eraser','desk','light','teacher','floor','wall','door','student','table','window','curtain','computer','mouse','keyboard'],
//['glue','scissors','notebook','ruler','white-out','eraser','sharpener','pencil','mechanical pencil','pencil case','highlighter'],
//['stones','bones','sticks','quill','ink','brush','pencil','pen','marker','crayon'],
//['ten','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety','hundred','thousand'],
//['hair','eyebrow','eye','nose','mouth','chest','stomach','leg','knee','foot','toe','head','neck','back','arm','elbow','finger','tongue','shoulder','hand','ankle','heel'],
//['touch your nose','stretch up high','clap your hands','bend down','shake your body','lift your leg','wave your arms','stomp your feet','spin around'],
//['happy','sad','nervous','relaxed','excited','energetic','tired','confused','scared','curious','bored','hungry','sleepy','angry','surprised','confident'],
//['bag','cap','doll','frog','girl','apple','elephant','insect','orange','umbrella','airplane','parrot','baby','hat','egg','rabbit','mouse','armchair'],
//['vision','touch','hear','smell','taste','colorful','music','yummy','animals','soft','bitter'],
//['skateboard','frisbee','football','robot','rubiks cube','basketball','guitar','puzzles','lego','hula hoop','doll','board game','yoyo','car'],
//['grandma','grandpa','uncle','aunt','me','dad','brother','mom','sister','puppy','cousin'],
//['january','february','march','april','may','june','july','august','september','october','november','december'],
//['first','second','third','fourth','fifth','sixth','seventh','eighth','ninth','tenth','eleventh','twelfth','thirteenth','fourteenth','fifteenth','sixteenth','seventeenth','eighteenth','nineteenth','twentieth'],
//['birthday','party','amazing','growth','interview','gift','year','special'],
//['apple','banana','grape','broccoli','cabbage','bread','rice','cereal','pasta','milk','cheese','meat','chicken','egg','strawberry','yogurt','carrot','fish','mushroom'],
//['apple','coconut','pomelo','lemon','pineapple','orange','mango','grapes','watermelon','kiwifruit','cherry','durian','eggplant','mushroom','strawberry','cauliflower','carrot','tomato','lettuce','potato','onion','corn','pumpkin'],
//['nutrients','carbohydrates','protein','fat','water','minerals','vitamins','body','healthy','muscles','energy'],
//['delicious','tasty','yummy','disgusting','salty','sweet','sour','bitter','spicy','stinky','chewy','tough'],
//['hat','cap','sunglasses','tie','bowtie','scarf','belt','socks','jacket','coat','vest','suit','sweater','sweatshirt','shirt','jeans','shorts','sweatpants','skirt','sandals','sneakers','flats','heels','slippers','boots'],
//['dress','shorts','t-shirt','skirt','tank top','pants','flip flops','dress','swimsuit','sunglasses','trunks','sandals','swimming trunks'],
//['red','yellow','green','blue','purple','orange','violet','white','black','gray','pink','indigo','dark','light'],
//['living room','dining room','bedroom','garage','kitchen','terrace','bathroom','yard'],
//['mirror','lamp','laptop','wardrobe','chair','rug','football','alarm clock','picture','bed'],
//['sort clothes','watch tv','make the bed','take a bath','brush teeth','organize toys','cook food','make cakes','wash the dishes','eat','set the table','clean up the table','mow the lawn','wash the car','walk the dog'],
//['comfortable','weather','cave','igloo','stilt house','house','place'],
//['parrot','shark','frog','owl','snake','stingray','seagull','elephant','whale','crocodile','bat','eel','jellyfish','spider','toad','frog'],
//['carnivore','herbivore','omnivore','mammal','bird','amphibian','reptile','fish','vertebrate','invertebrate'],
//['bird','mammal','reptile','fish','amphibian','animal'],
//['bird','mammal','reptile','fish','amphibian','warm-blooded','cold-blooded','wings','feathers','egg','scales'],
//['get up','make the bed','brush teeth','wash face','comb hair','have breakfast','go to school','watch tv','have dinner','do homework','go home','have lunch','have classes','take a shower','put on pajamas','go to bed'],
//['monday','tuesday','wednesday','thursday','friday','saturday','sunday'],
//['monday','tuesday','wednesday','thursday','friday','saturday','sunday','morning','afternoon','evening','breakfast','lunch','dinner'],
//['monday','tuesday','wednesday','thursday','friday','saturday','sunday','noon','easter','summer','june','afternoon','may','birthday','spring','morning'],
//['time','measure','sundial','sandglass','candle','clock','hourglass','sun','minute','hour'],
//['sunny','partly cloudy','cloudy','rainy','drizzling','stormy','snowy','sleeting','hailing','foggy','windy'],
//['january','february','march','april','may','june','july','august','september','october','november','december','summer','autumn','spring','winter'],
//['sunny','partly cloudy','cloudy','rainy','drizzling','stormy','snowy','sleeting','hailing','foggy','windy','frosty','warm','cold','hot','humid','wet','dry','cool'],
//['rain','grass','water','droplet','air','cloud','heavy','garden','vapor'],

//================ESL1=================

//['car','robot','doll','bike','teddy bear','ball'],
//['january','february','march','april','may','june','july','august','september','october','november','december'],
//['festival','harvest','leaves','crops','mooncake','dragon','meal','celebrate'],
//['we read books before bed','then we hug goodnight','my bed is soft and cozy','my cat sleeps with me','the sky has turned dark','my eyes close'],
//['hotel','movie theater','zoo','swimming pool','cafe','hospital','mall','library','park'],
//['movie theater','zoo','swimming pool','cafe','hospital','mall','hotel','library','park','east','west','north','south'],
//['truck','taxi','van','motorcycle','bus','car'],
//['firefighter','cleaner','doctor','chef','office worker','police officer','teacher','vet'],
//['science','animals','pets','veterinarian','sick','diet','healthy','owners'],
//['bread','turkey','green pepper','cucumber','tomato','mustard','egg'],
//['bananas','cabbages','potatoes','cucumbers','strawberries','carrots','peppers','grapes','oranges','pears','bread','turkey','tomatoes','mustard','eggs'],
//['bill','money','value','coin'],
//['tennis','gymnastics','volleyball','judo','basketball','ping-pong','football','baseball','badminton'],
//['exercise','body','healthy','stronger','lungs','heart','energy','muscles','stretch'],
//['dishwasher','lamp','candle','microwave','broom','kettle','washing','machine','vacuum','cleaner'],
//['history','study','place','people','question','answer','internet','object','museum','past','present','future'],
//['hair','long','straight','curly','short','beard','mustache','blond','black','glasses'],
//['president','leader','law','founder','government','nation','country','sign','grow','safe','happy'],
//['beak','feathers','fins','pouch','fur','tail','teeth','wings'],
//['snake','bat','bird','dolphin','crocodile','cave','sky','ocean','jungle','river'],
//['snorkeling','surfing','rock climbing','sailing','horse riding','mountain biking'],
//['freshwater','people','animal','ocean','salt','melting','insect','river','lake','mountain'],
//['mountain','island','volcano','lake','waterfall','desert','ocean','Pacific','Everest','Sahara','Greenland','Vesuvius','Arctic','Antarctica'],
//['freezing','warm','damp','foggy','chilly','stormy','icy','sunny','cloudy','stormy','rainy'],
//['astronaut','space','moon','spaceship','landed','stepped','footprint','rocks','soil','studied','flag'],

//================ESL2=================

//['germs','microscope','flashlight','infection','disease','medicine','vaccine','sick','sore throat','stomach ache','defense'],
//['lived','covered','prepared','worked','planted','fixed','flooded','cared','disappeared','harvested','used','saved'],
//['mayan','temple','palace','cotton','occasion','jewelry','jade','ordinary','gold','civilization'],
//['language','feeling','speak','country','gesture','meaning','polite','rude','acceptable','body','smile','index'],
//['mountain','island','volcano','lake','waterfall','desert','ocean','Pacific','Everest','Sahara','Greenland','Vesuvius','Amazon','Arctic'],
//['horseback riding','go shopping','go to the movies','listen to music','meet my friends','play computer games','stay home'],
//['astronaut','space','moon','spaceship','landed','stepped','footprint','rocks','soil','studied','flag'],
//['fresh','fruit','vegetables','snack','meal','sports','wash','prepare','sick','important','exercise','hygiene','sleep'],
//['astronomer','search','telescope','screen','planet','science','computer','object','moon','camera'],
//['awake','asleep','dark','light','rich','poor','up','down','day','night','long','short','big','small','old','young'],
//['technology','travel','place','walk','bicycle','car','wheel','motor','jet','engine','airplane'],

//================ESL3=================

//['stress','cope','reward','offline','exercise','manage','relax','challenge','overcome','difficulty','strategy','confident','exam','breathe'],
//['dream','travel','adventure','kilometer','camp','outdoors','cycle','baggage','traveller','journey','road','desert','rain forest','mountain'],
//['fields','hotels','cars','houses','horses','rivers','flowers','streets','taxis','peoples','dogs','mountains'],

//=================MEB=================

//['bike','block','ball','kite','marble','basketball','skateboard','boat','plane','toy','doll', 'football','soccer ball','guitar','toy box'],
//['apple tree','hawk','mushroom','carrot','dragonfly','bamboo','cougar','bacteria','daffodil','pigeon','snake','catfish','producer','consumer','decomposer'],
//['pudding','popcorn','sandwich','salad','yogurt','sugar','cheese','jam','pop','cola','toast','coffee','soup','pizza'],
//['kick a ball','catch a ball','sing songs','dance','ride a bike','jump rope','throw a ball','fly a kite','skate'],
//['flowers','lemonade','tea','apples','milk','eggs','bread','meat','chocolate','children','meat','matches','dogs','books','coca-cola'],
//['president','leader','founder','decide','law','country','nation','safe','happy'],
//['hat','dress','cap','scarf','shirt','jacket','skirt','pants','socks','shoes','coat','sweater','shoes'],

//================EXTRAS===============

//['sliding','swinging','riding','hiding','skating','jumping','climbing','flying','throwing','singing','kicking'],
//['went','saw','drank','put','had','bought','caught','ate','flew','drove','knew','made','ran','sang','slept','spoke','swam'],
//['go','meet','stay','play','listen','draw','dance','read','sleep','learn','write','eat','drink','have','see','watch','like','get','take'],
//['coke','juice','meat','cheese','ice cream','chocolate'],
//['star','snake','snail','sun','telephone','tent','tiger','taxi', 'tennis','sausage','umbrella'],
//['xenon','xerox','xylem'],
//['star','snake','snail','sun','telephone','tent','tiger','taxi'],
//['air','virus','hands','clean','wash','safe','mask','alcohol','sterilize','circulation'],
//['sweater','skirt','shirt','coat','hat','dress','jacket','scarf','pants','shorts','shoes','socks'],
//['fast','slow','happy','sad','tired','wet','open','heavy','dirty','tall','scared','hot','loud','bright','sticky','scary','beautiful','ugly','sweet','sharp'],
//['sore','throat','cough','backache','cold','fever','headache','stomach','ache','earache'],
//['coronavirus','mask','temperature','disinfection','alcohol','circulation','fever','cough','soap','sneeze'],
//['kangaroo','jacket','monster','monkey','octopus','lake','kite','piano','penguin','pig','lemon','queen'],
//['annoying','birthday','complete','criminal','everyone','exciting','everyday','exercise','language','mountain','thousand','tomorrow','whatever','whenever'],
//['a bag','a cap','a doll','a frog','a girl','an apple','an elephant','an insect','an orange','an umbrella','a car','an airplane','a parrot','a baby','a hat','an egg','a rabbit','a mouse','a snake','an armchair','a doll'],
//['ant','beluga','chameleon','cheetah','cobra','kangaroo','koala','komodo','mosquito','platypus','starfish','scorpion','owl','orca','rhino','panda','lion'],
//['tornado','typhoon','forest fire','tsunami','thunderstorm','earthquake','flood','eruption'],
//['rice flour','milk','mango','boiling water','cold water','chopsticks','juicer','bowl','disposable'],
//['cave','sky','ocean','jungle','river','forest','savannah','desert','tundra'],
//['sugar','warm water','colors','glass','blend','test tube','dropper','water bottle','spoon'],
//['jeep','jar','juice','jacket'],
//['mother','map','monkey','mouse'],
//['star','sun','snail','snake'],
//['hamburger','egg','carrot','hot dog','sausage','tomato','noodle','cookie','candy','dumpling','chip','sandwich','kiwifruit','pineapple','watermelon','grape','peach','strawberry'],
//['bat','pirate','superhero','dinosaur','robot','monkey'],


];