import os
import sys
from datetime import datetime
main_dir = os.getcwd()


filenames = {}

for folder in os.walk(main_dir):
    dir = os.path.basename(folder[0])
    if(len(dir) == 1):
        #is one of the letter dirs
        filenames[dir] = [name.split('.')[0] for name in folder[2]]
        
lines = [f"//This file was autogenerated from the file {sys.argv[0]}.","//Please do not manually edit it to avoid errors.", f"//Last generated on: {str(datetime.today().strftime('%Y-%m-%d-%H:%M:%S'))}"]

lines.append('\n\nlet KEYWORDS_CONFIG = {\n')
total_words = 0

for key,value in filenames.items():
    lines.append(f'\t{key}: {value},')
    total_words += len(value)

lines.append(f'\n\ttotal_words: {total_words},')
lines.append('\n};')


with open(os.path.join(main_dir,'keywords_config.js'),"w") as f:
    for line in lines:
        f.write(line + '\n')

print(f"Finished. Found {total_words} keywords.")