//This file was autogenerated from the file .\create_config.py.
//Please do not manually edit it to avoid errors.
//Last generated on: 2021-01-08-16:34:54


let KEYWORDS_CONFIG = {

	a: ['alligator', 'ant', 'apple', 'axe'],
	b: ['ball', 'bear'],
	c: ['cake', 'cap', 'car', 'cat'],
	d: ['dog', 'doll', 'dolphin', 'duck'],
	e: ['egg', 'elbow', 'elephant', 'envelope'],
	f: ['fan', 'fish', 'fox', 'frog'],
	g: ['garden', 'girl', 'goat', 'goose'],
	h: ['hat', 'hippo', 'horse', 'house'],
	i: ['igloo', 'in', 'ink', 'insect'],
	j: ['jacket', 'jar', 'jeep', 'juice'],
	k: ['kangaroo', 'key', 'kite', 'kitten'],
	l: ['lake', 'lamp', 'lemon', 'lion'],
	m: ['map', 'monkey', 'monster', 'mother', 'mouse'],
	n: ['night', 'nose', 'nurse'],
	o: ['october', 'octopus', 'on', 'open'],
	p: ['pencil', 'penguin', 'pig', 'pumpkin'],
	q: ['queen', 'question', 'quill', 'quilt', 'quiz'],
	r: ['rabbit', 'rhino', 'rocket', 'rooster'],
	s: ['snail', 'snake', 'star', 'sun'],
	t: ['taxi', 'telephone', 'tent', 'tiger', 'turtle'],
	u: ['umbrella', 'under', 'up'],
	v: ['vase', 'vegetables', 'vest', 'violin'],
	w: ['watch', 'water', 'window', 'wolf'],
	x: ['box', 'ox', 'xray'],
	y: ['yak', 'yogurt', 'yoyo'],
	z: ['zebra', 'zero', 'zipper', 'zoo'],

	total_words: 101,

};
